console.log(typeof 111);
console.log(typeof 1.11);
console.log(typeof "111");
console.log(typeof true);
console.log(typeof null);
var a;
console.log(typeof a);
console.log(typeof []);
console.log(typeof {});
console.log(typeof function f(){});